services:
  - type: web
    env: python
    name: health-fall-detection
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: gunicorn health_fall_detection.wsgi:application
